"""empty message

Revision ID: 201338506df8
Revises: 8b3f542d1455
Create Date: 2016-01-03 22:49:41.455221

"""

# revision identifiers, used by Alembic.
revision = '201338506df8'
down_revision = '8b3f542d1455'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Prices', sa.Column('price_key', sa.String(), nullable=True))
    op.drop_column('Prices', 'size')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Prices', sa.Column('size', sa.VARCHAR(), nullable=True))
    op.drop_column('Prices', 'price_key')
    ### end Alembic commands ###
