"""empty message

Revision ID: 8b3f542d1455
Revises: None
Create Date: 2016-01-03 18:05:30.596219

"""

# revision identifiers, used by Alembic.
revision = '8b3f542d1455'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cafes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slack_team_id', sa.String(), nullable=True),
    sa.Column('slack_user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('tutor', sa.Boolean(), nullable=True),
    sa.Column('teacher', sa.Boolean(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('alerts', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('objtype', sa.String(), nullable=True),
    sa.Column('objid', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafeid', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cafeid'], ['Cafes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RegistrationIDs',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('regid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('userid', 'regid')
    )
    op.create_table('Runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cafeid', sa.Integer(), nullable=True),
    sa.Column('pickup', sa.String(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cafeid'], ['Cafes.id'], ),
    sa.ForeignKeyConstraint(['person'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('money_exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payerid', sa.Integer(), nullable=True),
    sa.Column('payeeid', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payeeid'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['payerid'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Coffees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.Integer(), nullable=True),
    sa.Column('coffee', sa.String(), nullable=True),
    sa.Column('runid', sa.Integer(), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('starttime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('endtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['person'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['runid'], ['Runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Coffees')
    op.drop_table('money_exchange')
    op.drop_table('Runs')
    op.drop_table('RegistrationIDs')
    op.drop_table('Prices')
    op.drop_table('Events')
    op.drop_table('Users')
    op.drop_table('Cafes')
    ### end Alembic commands ###
